### ISSUE TITLE
Endpoint /block

### ISSUE THREAD

**Issue by raynaudoe** [Zondax/rosetta-filecoin#1]
Rosetta allows the `/block` request to have the fields `request.BlockIdentifier.Index` and `request.BlockIdentifier.Hash`.

Since the response doesn't allow to retrieve a list of Blocks, and in Filecoin several Blocks can share the same height, when doing:

 `request.BlockIdentifier.Index` : Should it return the Tipset at the height `Index` ?

 `request.BlockIdentifier.Hash` : Should it return the Tipset with CID `Hash` ?

**Comment by qiwu7** [comment]
Hi! This is Qi from Coinbase. I have a quick comment on this. 

We will definitely need the ability to uniquely identify a tipset. The current [approach](https://github.com/Zondax/lotus/blob/rosetta_integration/rosetta/services/block.go#L59) where you simply take the first Block CID with a tipset `tipset.Cids()[0]` will not be able to work for us. Imagine during a reorg, the first `Block` within a `tipset` might stay the same while the rest of the blocks might change. With the current approach the `BlockIdentifier.Hash` will remain the same, but actually the it should be a different value since the TipSet changes. We will definitely need the `BlockIdentifier.Hash` to identify the content the `TipSet` uniquely not a block of the TipSet.

Proposal: We recommend using [types.TipSetKey](https://github.com/filecoin-project/lotus/blob/7e0be91cfd44c1664ac18f81080544b1341872f1/chain/types/tipset_key.go#L29-L42) to hash a slice of CIDS (Block CIDs within a TipSet) so we will be able to uniquely identify the tipset.

Additional Questions:
- Transactions: 
    - We need to be able to retrieve all transactions with a TipSet, not just transactions for a Single Block within the TipSet. So you would need to
    - Filecoin messages have 2 phases: inclusion in TipSet H, and execution in TipSet H + 1. The first phase only does some validation checks but does not cause any state change. The second phase, which occurs 1 Ledger after the first, executes the message, producing a state change and a receipt. This method should only returns the transactions which were *executed* in a given ledger, not those that were included.

**Comment by raynaudoe** [comment]
Hi Qi, thanks for the comments!

- Ok, I'm already working on using `TipSetKey` in order to cover Coinbase's needs.
- Yes, the above change will make retrieving all transactions from all blocks within a Tipset.
- I'm not sure if the messages retrieved from a block corresponds to the ones on the **executed** state only, I'll check that matter with Filecoin.

**Comment by qiwu7** [comment]
Also logged a similar issue [here](https://github.com/Zondax/rosetta-filecoin/issues/3) for NetworkStatus

**Comment by qiwu7** [comment]
Recommend reading [spec](https://filecoin-project.github.io/specs/#systems__filecoin_vm__interpreter)

**Comment by qiwu7** [comment]
/block endpoint should also includes the List of Block CIDs within a TipSet in the Block metadata field.

**Comment by qiwu7** [comment]
Also what are all different types of operations we are going to support? I see the following being interested operations for us at the moment. Noted that Transfer operation should include both a normal send from a regular address and a msig send from a smart contract call.
- Transfer
- Fee
- Reward

**Comment by qiwu7** [comment]
Another BUG that I want to report is when I fetch genesis block from the `/block` endpoint, I am getting "unable to get parent block" error.

request
```
{
    "network_identifier": {
        "blockchain": "Filecoin",
        "network": "testnet"
    },
    "block_identifier": {
        "index": 0
    }
}
```

response
```
{
    "code": 23,
    "message": "unable to get parent block",
    "retriable": true
}
```

**Comment by raynaudoe** [comment]
Ok, should be fixed on the next PR

**Comment by qiwu7** [comment]
@raynaudoe want to add some additional comments on Transaction Operations. We want to make sure we populate related operations for a transaction operation. I recommend reading though this section of the [blog post](https://www.rosetta-api.org/blog/2020/06/17/1-try-celo-rosetta.html#view-block-3530) at least to get a butter understanding on how the related operations should be populated for a simple transfer.

**Comment by raynaudoe** [comment]
Ok, checking on that.

**Comment by qiwu7** [comment]
Got error when fetching genesis block
```
curl --location --request POST '{{NODE_URL}}/block' \
--header 'Content-Type: application/json' \
--data-raw '{
    "network_identifier": {
        "blockchain": "Filecoin",
        "network": "testnet"
    },
    "block_identifier": {
        "index": 0,
        "hash": "0171a0e402201c1fb0c2e62d1857e523ea79898051c91e4b042c2ed96c4995c5002789570a21"
    }
}'
```

response
```
{
    "code": 22,
    "message": "unable to get tipset",
    "retriable": true
}
```

**Comment by qiwu7** [comment]
Ok Another followup on this..

response from get genesis block
```
{
    "block": {
        "block_identifier": {
            "index": 0,
            "hash": "0171a0e402201c1fb0c2e62d1857e523ea79898051c91e4b042c2ed96c4995c5002789570a21"
        },
        "parent_block_identifier": {
            "index": 0,
            "hash": ""
        },
        "timestamp": 1592524800000,
        "transactions": null,
        "metadata": {
            "blockCIDs": [
                "bafy2bzacednghy3w2e42xqrgeisswleti2uf2dno4ffaieuge2wfrbigqwdv6"
            ]
        }
    }
}
```

Asserter.Block is checking none empty for ParentBlockIdentifier.Hash [here](https://github.com/coinbase/rosetta-sdk-go/blob/master/asserter/block.go#L365).

We need to populate the parent hash as well

**Comment by jleni** [comment]
We intentionally left that blank. 
The genesis block has no parent. What would be the parent of genesis?

Would it make sense to fix the Asserter instead?

**Comment by jleni** [comment]
It sounds to me that these lines:

https://github.com/coinbase/rosetta-sdk-go/blob/f929bfc4a262afbbb4053570664be00053a0b657/asserter/block.go#L365-L367

should be placed here:

https://github.com/coinbase/rosetta-sdk-go/blob/f929bfc4a262afbbb4053570664be00053a0b657/asserter/block.go#L372

**Comment by qiwu7** [comment]
I need to ask @patrick about this. Let me get back to you.

**Comment by qiwu7** [comment]
I will still need to double check with Patrick to confirm, but It seems we can just return the genesis block itself for the `parent_block_identifier`.
[Celo](https://github.com/celo-org/rosetta/blob/b4f96987ff57774d740eee9ccf8da28436674540/service/rpc/rosetta_transforms.go#L74-L82) has implemented it this way.

**Comment by jleni** [comment]
Well, that's actually a hack to avoid fixing the asserter :)

**Comment by jleni** [comment]
we can do that and document it

**Comment by qiwu7** [comment]
It seems we already had a post in the CommonMistake section [here](https://www.rosetta-api.org/docs/common_mistakes.html#malformed-genesis-block). I was not aware. But basically it’s been a pattern that we have been following within our system, and it’s easier to assert that every block has a parent and we can easily tell if a block (out of context) is genesis. But you are correct that genesis has no parent. This is just how we chose to represent it. (This is very arbitrary TBH)

**Comment by raynaudoe** [comment]
We can close this since the issue of adding genesis's parent block is already solved (also, there's now a test for this exclusively).
We can keep track of the "supported operations" issue mentioned here on #11.
