### ISSUE TITLE
Dockerfile improvements

### ISSUE THREAD

**Issue by qiwu7** [Zondax/rosetta-filecoin#19]
### Issues
- Error handling
  - Lotus stoped syncing from time to time and we cannot see any errors in the log.
  - node shut down is pretty slow… take more than 300s. This is related to the dockerfile shell scripts we believe.
- start.sh script (when using `lotus deamon --import-snapshot)
  - it starts importing but does not respond to APIs. 
  - start script they gets the error back but considers it ok and starts rosetta
  - rosetta connects 10x and fails, then exists, causing container to reset

### Asks
**Error handling**
- [x] modify dockerfile to have docker container exit properly whenever there is an unexpected error from either rosetta-proxy  or lotus. Currently the shell script starts lotus in the background and does not surface any error to us. The docker container is still running while lotus node stopped.
- [x] double check dockerfile to ensure we log errors from both `rosetta-proxy` and `louts`

**start.sh script**
- [x] the start script needs to pass any arguments it receives to the node itself (enables us to do things like snapshot imports)
- [x] rosetta proxy should keep retrying connection to lotus API in an endless loop
- [x] if any component (rosetta proxy or lotus itself) exits unexpectedly the whole container needs to exit
- [x] hanging on the APIs is not an exit condition, i.e. if lotus keeps locked up but the process is running we keep running

**Comment by jleni** [comment]
Additional points:
- environment error level
- log process name on exit
- tagged version

**Comment by jleni** [comment]
- I have created an independent issues for release pinning
- environment error level has been set in the Dockerfile
- We investigated process name logging as part of the start script. Process parallel may introduce additional complexity. We decided to skip this optional item for now.
