### ISSUE TITLE
Hardcoded CPU info

### ISSUE THREAD

**Issue by rllola** [Zondax/rosetta-filecoin#29]
When starting a devnet docker I had this error :
```
docker run "-t" "-i" --rm --dns 8.8.8.8 -m 30823244kB --cpus="16" --oom-kill-disable --ulimit nofile=90000:90000 --name filecoin-devnet -p 1235:1234 zondax/filecoin-devnet:latest 
docker: Error response from daemon: Range of CPUs is from 0.01 to 8.00, as there are only 8 CPUs available.
```

I believe it is because it hardcoded to be 16 CPUs.
https://github.com/Zondax/rosetta-filecoin/blob/d779d98eed9839bb730f13fc7f4623285fbdb553/Makefile#L63

**Comment by rllola** [comment]
Using `$(shell nproc)` would avoid hardcoding values.

**Comment by jleni** [comment]
Definitely, sounds like a very easy fix

Just for a complete solution.. here is something that also works in MacOS

https://github.com/Zondax/ledger-dfinity/blob/9c0e638ba483ec8cecc9740e9c3d6cd373ff98cc/deps/ledger-zxlib/dockerized_build.mk#L53-L59

**Comment by emmanuelm41** [comment]
In MacOS 11.4, this doesn't work either. /proc/meminfo is not present. 

`MAX_RAM:=$(shell grep MemTotal /proc/meminfo | awk '{print $$2 $$3}')`

**Comment by jleni** [comment]
I fixed this in some other ledger apps. I think a good reference is the
polkadot app.
