### ISSUE TITLE
Analyse and remove circleci

### ISSUE THREAD

**Issue by jleni** [Zondax/rosetta-filecoin#38]
@emmanuelm41 
Do we still need circleci in this repo?

**Comment by emmanuelm41** [comment]
No, we don't. But I cannot remove it... @jleni you should do it.

<img width="936" alt="image" src="https://user-images.githubusercontent.com/10941036/122592222-64a2bf00-d03a-11eb-986a-6b1405005a4f.png">

**Comment by jleni** [comment]
done
